id: P56C34DC4
initial_creation_type: input
source_metadata:
  title: Medicine Buddha
  language: bo
  description: 'Texts related to the Medicine Buddha or Bhaiṣajya Guru (sman bla),
    Lord of Physicians:'
  volume:
    b9c8708b6958435aa30666de9ddb8759:
      title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
      parent: Practices
    fe9b584322d847069a3977d0d898a1ff:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Sādhanas
    ac20646e6a1b4b02806c67e4ecd1cb9c:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Sādhanas
    322c42076f3946fa9457e727856333e3:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Sādhanas
created_at: '2022-03-01T04:39:26.198700'
last_modified_at: '2022-03-01T04:39:26.198703'
statistics:
  total_words: 1477
  total_non_words: 229
quality:
  non_words_ratio: 0.16
